# Gradle settings
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# Minecraft/NeoForge Properties
minecraft_version=1.21.1
neoforge_version=21.1.217

# Mod Properties
mod_version=0.5.0
mod_id=things
mod_name=Things
mod_license=MIT
mod_authors=glisco
maven_group=com.glisco
archives_base_name=things

# Dependencies
# https://maven.theillusivec4.top/top/theillusivec4/curios/curios-neoforge/
curios_version=9.2.2+1.21.1

# https://maven.wispforest.io/releases/io/wispforest/owo-lib-neoforge/
owo_version=0.12.15.1-beta.6+1.21

# https://maven.shedaniel.me/me/shedaniel/RoughlyEnoughItems-neoforge/
rei_version=16.0.788

# https://maven.shedaniel.me/me/shedaniel/cloth/cloth-config-neoforge/
cloth_config_version=15.0.140

# https://maven.architectury.dev/dev/architectury/architectury-neoforge/
architectury_version=13.0.8
